### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 3ck0o**

### CODE REVIEW

**Comment by 3ck0o** [comment]
Detected errors

**Comment by Ezwal** [comment]
sorry we don't take pull request

**Comment by vouill** [comment]
👍

**Comment by 3ck0o** [comment]
:+1:

**Comment by Ezwal** [comment]
@3ck0o if you can squatch it I can integrate it to the repo thanks.

**Comment by vouill** [comment]
LGTM

**Comment by Ezwal** [comment]
I asked a for more than half a month to squash this change set and yet you didn't...
Seems like you're lazy

**Pull request closed without merging**
